// import { Store } from "types";

// export const state: Store = {
//   routine: {
//     rungs: {
//       byId: {
//         rung1: {
//           id: "rung1",
//           type: "Rung",
//           child: "branch1",
//           comment:
//             "A conveyor carries widgets to a robotic arm which will pack them into a box.\nThe conveyor stops when the robotic arm is moving a box of widgets.",
//         },
//         rungMWgOP31sngquEOxBh4Evp: {
//           id: "rungMWgOP31sngquEOxBh4Evp",
//           type: "Rung",
//           child: "branchEn5DJ7AKZ1EVXLJobWJxE",
//           comment:
//             "A new widget arrives at the end of the conveyor every 2 seconds.",
//         },
//         rungPB5fnJq1G8L98R7dGjPN5: {
//           id: "rungPB5fnJq1G8L98R7dGjPN5",
//           type: "Rung",
//           child: "branchKmjWttevjEJMKuhDn1Uju",
//         },
//         rung63xeJL15ukSA2YgVf8ai8: {
//           id: "rung63xeJL15ukSA2YgVf8ai8",
//           type: "Rung",
//           child: "branchf8GbDQkZIyb2323h4j8k2",
//           comment:
//             "Once 5 widgets have been packed, the robotic arm needs to move the box.\nThis resets the widget count.",
//         },
//         "rungDYHIGLV-WGo9rLuOPcwe8": {
//           id: "rungDYHIGLV-WGo9rLuOPcwe8",
//           type: "Rung",
//           child: "branch4SPx5elppiEFTCsS-1N3I",
//           comment:
//             "The number of boxes produced is stored.\nAn add instruction is used instead of a counter because there is no target number of boxes.",
//         },
//       },
//       allIds: [
//         "rung1",
//         "rungMWgOP31sngquEOxBh4Evp",
//         "rungPB5fnJq1G8L98R7dGjPN5",
//         "rung63xeJL15ukSA2YgVf8ai8",
//         "rungDYHIGLV-WGo9rLuOPcwe8",
//       ],
//     },
//     branches: {
//       branch1: {
//         id: "branch1",
//         type: "AND",
//         parent: "rung1",
//         children: [
//           "instructionXN6Y6bgPFb3ofuCltyILH",
//           "instructionRD1icSN2yRGLoT8StlFWD",
//         ],
//       },
//       branchEn5DJ7AKZ1EVXLJobWJxE: {
//         id: "branchEn5DJ7AKZ1EVXLJobWJxE",
//         type: "AND",
//         parent: "rungMWgOP31sngquEOxBh4Evp",
//         children: [
//           "instructionhk_bNH_W8pfyKbTJrIbfK",
//           "instruction5NHX5Y03S6tpLN3qxEJt1",
//           "instructionNlwAHH0mrI-3SScd42ADf",
//         ],
//       },
//       branchKmjWttevjEJMKuhDn1Uju: {
//         id: "branchKmjWttevjEJMKuhDn1Uju",
//         type: "AND",
//         parent: "rungPB5fnJq1G8L98R7dGjPN5",
//         children: [
//           "instructionbhFWBFskWBDO3Q_NJeTqt",
//           "instruction6Ra2FSDgP9ZPRQCuYt1Fw",
//         ],
//       },
//       branchf8GbDQkZIyb2323h4j8k2: {
//         id: "branchf8GbDQkZIyb2323h4j8k2",
//         type: "AND",
//         parent: "rung63xeJL15ukSA2YgVf8ai8",
//         children: [
//           "instructionSi8BBMGdbo4g_SiRdPa5B",
//           "branchoVQTEpAwdAqHphPDcyQaC",
//         ],
//       },
//       branchoVQTEpAwdAqHphPDcyQaC: {
//         id: "branchoVQTEpAwdAqHphPDcyQaC",
//         type: "OR",
//         parent: "branchf8GbDQkZIyb2323h4j8k2",
//         children: [
//           "branchWb3WAeQuAP1vFh3GcgOWm",
//           "branch1xtTrVbiS1K40kmQITPQI",
//         ],
//       },
//       branchWb3WAeQuAP1vFh3GcgOWm: {
//         id: "branchWb3WAeQuAP1vFh3GcgOWm",
//         type: "AND",
//         parent: "branchoVQTEpAwdAqHphPDcyQaC",
//         children: ["instruction4W840DD9zh6xvVbiihc7D"],
//       },
//       branch1xtTrVbiS1K40kmQITPQI: {
//         id: "branch1xtTrVbiS1K40kmQITPQI",
//         type: "AND",
//         parent: "branchoVQTEpAwdAqHphPDcyQaC",
//         children: [
//           "instructionLXcwXi0Z7uk9o_XvlSHKS",
//           "instructionx5x4vQILc7PJ8C8LGB48n",
//         ],
//       },
//       "branch4SPx5elppiEFTCsS-1N3I": {
//         id: "branch4SPx5elppiEFTCsS-1N3I",
//         type: "AND",
//         parent: "rungDYHIGLV-WGo9rLuOPcwe8",
//         children: [
//           "instructionatfIqxZ7pssaAJ3JZQhuV",
//           "instructionc05DpIcLUiE-ARX3SCr68",
//           "instructionbPmM3Cvln7KcwQO43xO_6",
//         ],
//       },
//     },
//     instructions: {
//       instructionRD1icSN2yRGLoT8StlFWD: {
//         id: "instructionRD1icSN2yRGLoT8StlFWD",
//         type: "Instruction",
//         displayType: "Special",
//         abbreviated: "OTE",
//         tag: "Conveyor",
//         parent: "branch1",
//         isDestructive: true,
//         energized: true,
//       },
//       instruction5NHX5Y03S6tpLN3qxEJt1: {
//         id: "instruction5NHX5Y03S6tpLN3qxEJt1",
//         type: "Instruction",
//         displayType: "Special",
//         abbreviated: "XIC",
//         tag: "Conveyor",
//         parent: "branchEn5DJ7AKZ1EVXLJobWJxE",
//         isDestructive: false,
//         energized: true,
//       },
//       instructionXN6Y6bgPFb3ofuCltyILH: {
//         id: "instructionXN6Y6bgPFb3ofuCltyILH",
//         type: "Instruction",
//         displayType: "Special",
//         abbreviated: "XIO",
//         tag: "Robotic Arm.tt",
//         parent: "branch1",
//         isDestructive: false,
//         energized: true,
//       },
//       "instructionNlwAHH0mrI-3SScd42ADf": {
//         id: "instructionNlwAHH0mrI-3SScd42ADf",
//         type: "Instruction",
//         name: "Timer On Delay",
//         description: "",
//         displayType: "Box",
//         abbreviated: "TON",
//         parameters: {
//           Timer: { key: "Timer", value: "Widget", type: "timer" },
//           pre: { key: "pre", value: 2, type: "number" },
//           acc: { key: "acc", value: 0, type: "number" },
//           dn: { key: "dn", value: false, type: "bool", hidden: true },
//           tt: { key: "tt", value: true, type: "bool", hidden: true },
//           startTime: {
//             key: "startTime",
//             value: 1691520202578,
//             type: "number",
//             hidden: true,
//           },
//         },
//         parent: "branchEn5DJ7AKZ1EVXLJobWJxE",
//         isDestructive: true,
//         energized: false,
//       },
//       instructionhk_bNH_W8pfyKbTJrIbfK: {
//         id: "instructionhk_bNH_W8pfyKbTJrIbfK",
//         type: "Instruction",
//         displayType: "Special",
//         abbreviated: "XIO",
//         tag: "Widget.dn",
//         parent: "branchEn5DJ7AKZ1EVXLJobWJxE",
//         isDestructive: false,
//         energized: true,
//       },
//       instructionbhFWBFskWBDO3Q_NJeTqt: {
//         id: "instructionbhFWBFskWBDO3Q_NJeTqt",
//         type: "Instruction",
//         displayType: "Special",
//         abbreviated: "XIC",
//         tag: "Widget.dn",
//         parent: "branchKmjWttevjEJMKuhDn1Uju",
//         isDestructive: false,
//         energized: false,
//       },
//       instruction6Ra2FSDgP9ZPRQCuYt1Fw: {
//         id: "instruction6Ra2FSDgP9ZPRQCuYt1Fw",
//         type: "Instruction",
//         name: "Count Up",
//         description: "",
//         displayType: "Box",
//         abbreviated: "CTU",
//         parameters: {
//           Counter: {
//             key: "Counter",
//             value: "Widgets Produced",
//             type: "counter",
//           },
//           pre: { key: "pre", value: 5, type: "number" },
//           acc: { key: "acc", value: 0, type: "number" },
//           dn: { key: "dn", value: false, type: "bool", hidden: true },
//         },
//         parent: "branchKmjWttevjEJMKuhDn1Uju",
//         isDestructive: true,
//         energized: false,
//       },
//       instructionSi8BBMGdbo4g_SiRdPa5B: {
//         id: "instructionSi8BBMGdbo4g_SiRdPa5B",
//         type: "Instruction",
//         displayType: "Special",
//         abbreviated: "XIC",
//         tag: "Widgets Produced.dn",
//         parent: "branchf8GbDQkZIyb2323h4j8k2",
//         isDestructive: false,
//         energized: false,
//       },
//       instruction4W840DD9zh6xvVbiihc7D: {
//         id: "instruction4W840DD9zh6xvVbiihc7D",
//         type: "Instruction",
//         name: "Timer On Delay",
//         description: "",
//         displayType: "Box",
//         abbreviated: "TON",
//         parameters: {
//           Timer: { key: "Timer", value: "Robotic Arm", type: "timer" },
//           pre: { key: "pre", value: 3, type: "number" },
//           acc: { key: "acc", value: 0, type: "number" },
//           dn: { key: "dn", value: false, type: "bool", hidden: true },
//           tt: { key: "tt", value: false, type: "bool", hidden: true },
//           startTime: {
//             key: "startTime",
//             value: 1691520199399,
//             type: "number",
//             hidden: true,
//           },
//         },
//         parent: "branchWb3WAeQuAP1vFh3GcgOWm",
//         isDestructive: true,
//         energized: false,
//       },
//       instructionLXcwXi0Z7uk9o_XvlSHKS: {
//         id: "instructionLXcwXi0Z7uk9o_XvlSHKS",
//         type: "Instruction",
//         displayType: "Special",
//         abbreviated: "XIC",
//         tag: "Robotic Arm.dn",
//         parent: "branch1xtTrVbiS1K40kmQITPQI",
//         isDestructive: false,
//         energized: false,
//       },
//       instructionx5x4vQILc7PJ8C8LGB48n: {
//         id: "instructionx5x4vQILc7PJ8C8LGB48n",
//         type: "Instruction",
//         name: "Move",
//         description: "A -> B",
//         displayType: "Box",
//         abbreviated: "MOV",
//         parameters: {
//           A: { key: "A", value: "0", type: "number" },
//           B: { key: "B", value: "Widgets Produced.acc", type: "number" },
//         },
//         parent: "branch1xtTrVbiS1K40kmQITPQI",
//         isDestructive: true,
//         energized: false,
//       },
//       instructionatfIqxZ7pssaAJ3JZQhuV: {
//         id: "instructionatfIqxZ7pssaAJ3JZQhuV",
//         type: "Instruction",
//         displayType: "Special",
//         abbreviated: "XIC",
//         tag: "Robotic Arm.dn",
//         parent: "branch4SPx5elppiEFTCsS-1N3I",
//         isDestructive: false,
//         energized: false,
//       },
//       instructionbPmM3Cvln7KcwQO43xO_6: {
//         id: "instructionbPmM3Cvln7KcwQO43xO_6",
//         type: "Instruction",
//         name: "Add",
//         description: "A + B = C",
//         displayType: "Box",
//         abbreviated: "ADD",
//         parameters: {
//           A: { key: "A", value: "Boxes of Widgets", type: "number" },
//           B: { key: "B", value: "1", type: "number" },
//           C: { key: "C", value: "Boxes of Widgets", type: "number" },
//         },
//         parent: "branch4SPx5elppiEFTCsS-1N3I",
//         isDestructive: true,
//         energized: false,
//       },
//       "instructionc05DpIcLUiE-ARX3SCr68": {
//         id: "instructionc05DpIcLUiE-ARX3SCr68",
//         type: "Instruction",
//         displayType: "Special",
//         abbreviated: "ONS",
//         tag: null,
//         parent: "branch4SPx5elppiEFTCsS-1N3I",
//         isDestructive: false,
//         energized: false,
//       },
//     },
//   },
//   tags: {
//     byId: {
//       Widget: {
//         name: "Widget",
//         type: "timer",
//         value: {
//           pre: 2,
//           acc: 0,
//           dn: false,
//           tt: true,
//           startTime: 1691520202578,
//         },
//       },
//       "Robotic Arm": {
//         name: "Robotic Arm",
//         type: "timer",
//         value: {
//           pre: 3,
//           acc: 0,
//           dn: false,
//           tt: false,
//           startTime: 1691520199399,
//         },
//       },
//       "Widgets Produced": {
//         name: "Widgets Produced",
//         type: "counter",
//         value: { pre: 5, acc: 0, dn: false },
//       },
//       Conveyor: { name: "Conveyor", type: "bool", value: true },
//       "Boxes of Widgets": {
//         name: "Boxes of Widgets",
//         type: "number",
//         value: 0,
//       },
//     },
//     allIds: [
//       "Conveyor",
//       "Widget",
//       "Widgets Produced",
//       "Robotic Arm",
//       "Boxes of Widgets",
//     ],
//   },
//   draggingRung: false,
//   whichDraggingRung: null,
//   draggingInstruction: false,
//   whichDraggingInstruction: null,
//   dropLocations: {
//     branch1: [0, 1],
//     branchEn5DJ7AKZ1EVXLJobWJxE: [0, 1, 2],
//     branchKmjWttevjEJMKuhDn1Uju: [0, 1],
//     branchf8GbDQkZIyb2323h4j8k2: [0, 1],
//     branchWb3WAeQuAP1vFh3GcgOWm: [0],
//     branch1xtTrVbiS1K40kmQITPQI: [0, 1],
//     "branch4SPx5elppiEFTCsS-1N3I": [0, 1],
//   },
//   rungDropLocations: null,
//   editMode: false,
//   runSimulation: false,
//   tagsAreUnassigned: false,
// };
